/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 map_point.glb 
Author: fijaya (https://sketchfab.com/fijaya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/map-point-837ad8ab50d24ee3a768c1ecd33c51c7
Title: Map Point
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PointUnit(props) {
  const { nodes, materials } = useGLTF('./models/map_point.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.06, 5.654, -1.314]} rotation={[Math.PI / 2, 0.005, 0]} scale={[3.045, 3.045, 4.727]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} position={[3.882, 0, -3.859]} />
    </group>
  )
}

useGLTF.preload('/map_point.glb')
