/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 treeModel_2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TreeModelTwo(props) {
  const { nodes, materials } = useGLTF('./models/trees/treeModel_2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCone1004.geometry} material={materials.lambert15} position={[0.892, 0.382, 0.014]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.pCone2004.geometry} material={materials.lambert14} position={[0.892, 0.382, 0.014]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.pCone3004.geometry} material={materials.lambert13} position={[0.892, 0.382, 0.014]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.pCone4004.geometry} material={materials.lambert12} position={[0.892, 0.382, 0.014]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.pCylinder3005.geometry} material={materials.lambert16} position={[0.892, 0.382, 0.014]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
    </group>
  )
}

useGLTF.preload('./models/trees/treeModel_2.glb')
