/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 treeModel_1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TreeModelOne(props) {
  const { nodes, materials } = useGLTF('./models/trees/treeModel_1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder1007.geometry} material={materials.lambert18} position={[-0.187, 0.285, -2.113]} rotation={[Math.PI / 2, 0, -1.357]} scale={0.011} />
      <mesh geometry={nodes.pPlatonic1006.geometry} material={materials.lambert11} position={[-0.187, 0.285, -2.113]} rotation={[Math.PI / 2, 0, -1.357]} scale={0.011} />
      <mesh geometry={nodes.pPlatonic2006.geometry} material={materials.lambert11} position={[-0.187, 0.285, -2.113]} rotation={[Math.PI / 2, 0, -1.357]} scale={0.011} />
      <mesh geometry={nodes.pPlatonic3006.geometry} material={materials.lambert11} position={[-0.187, 0.285, -2.113]} rotation={[Math.PI / 2, 0, -1.357]} scale={0.011} />
      <mesh geometry={nodes.pPlatonic4006.geometry} material={materials.lambert11} position={[-0.187, 0.285, -2.113]} rotation={[Math.PI / 2, 0, -1.357]} scale={0.011} />
      <mesh geometry={nodes.pPlatonic5006.geometry} material={materials.lambert11} position={[-0.187, 0.285, -2.113]} rotation={[Math.PI / 2, 0, -1.357]} scale={0.011} />
    </group>
  )
}

useGLTF.preload('/treeModel_1.glb')
